In [ ]:
import numpy as np
import pandas as pd
from collections import namedtuple
import random
from math import isclose
import pdb

In [ ]:
Stats = namedtuple('Stats', ['mean', 'std'])

## Fake data generator

In [ ]:
from nn4tab.test_utils import fake_data

In [ ]:
df, cont_names, cat_names = fake_data(preproc=False)

In [ ]:
df.head()

cont_0    cont_1    cont_2    cont_3    cont_4  cat_0  cat_1  targ
0 -1.738266 -1.336643 -1.361107 -0.351617 -2.312582      2      1   0.0
1 -0.188897 -0.957229  0.893600  0.956847  1.392258      0      0   1.0
2  0.767470 -0.053030  0.859794  1.505481 -0.653595      0      1   1.0
3  0.610351 -0.042674  1.440017 -0.836895 -0.301547      2      1   1.0
4  0.362339  0.258110 -1.639448  0.360155 -0.118498      2      1   1.0

In [ ]:
def print_stat(df):
    for col in cont_names:
        print(f'{col}: mean={df[col].mean():.4f}, std ={df[col].std():.4f}')

In [ ]:
for col in cont_names:
    print('mean: ', df[col].mean())
    print('std: ', df[col].std())
#     assert isclose(df[col].mean(), stat[col].mean)
#     assert isclose(df[col].std(), stat[col].std)

mean:  -1.6134366
std:  2.5976331
mean:  4.811953
std:  2.708622
mean:  -1.8439788
std:  2.4517055
mean:  2.847352
std:  1.4774374
mean:  3.693561
std:  2.97212


In [ ]:
rng = np.random.default_rng(0)
a = rng.standard_normal(size=(1000,1000))
# a = a*2 + 5

In [ ]:
means, stds = a.mean(axis=0), a.std(axis=0)
means.std(), stds.std()

## Data preprocessing

In [ ]:
from nn4tab.data import Normalize, FillMissing, Categorify

## Datasets and dataloaders

In [ ]:
from nn4tab.data import cont_cat_split, TabularDataset, get_dsets

In [ ]:
dep_var = 'targ'

In [ ]:
cont, cat = cont_cat_split(df, dep_var)

In [ ]:
assert cont==cont_names

In [ ]:
assert cat==cat_names

In [ ]:
train_ds, valid_ds = get_dsets(df, cat, cont, [dep_var])

In [ ]:
train_ds[0]

(array([2, 2]),
 array([-0.46469232,  0.6805593 ,  0.9084532 ,  0.9904088 , -0.2751088 ],
       dtype=float32),
 array([1.], dtype=float32))

In [ ]:
train_ds.data[dep_var].mean(), valid_ds.data['targ'].mean()

(0.66625, 0.665)